version: '2.3'
services:
    padawan:
        build: .
        image: padawan
        network_mode: "host"
        privileged: true
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - "$PWD:/catkin_ws/"
